[package]

name        = "nix"
description = "Rust friendly bindings to *nix APIs"
version     = "0.4.0"
authors     = ["Carl Lerche <me@carllerche.com>"]
homepage    = "https://github.com/carllerche/nix-rust"
license     = "MIT"
exclude     = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*"
]

[features]

eventfd = []
execvpe = []

[dependencies]
libc     = "0.1.10"
bitflags = "0.3.2"

[dev-dependencies]
rand = "0.3.8"

[dev-dependencies.nix-test]
path    = "nix-test"
version = "*"

[[test]]

name = "test"
path = "test/test.rs"
